### ISSUE TITLE
element with class row overflows on left and right side of editorView

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#148]
### Bug
Since merging the most recent develop version we have an issue in the editor that the components are overflowing.

### Cause
This is due to `_grid.scss:24` having a `margin-left: -15px` for some strange reasons

### Screenshots
<img width="356" alt="Screenshot 2019-07-16 at 13 15 52" src="https://user-images.githubusercontent.com/50131232/61290466-3b34e500-a7cc-11e9-9ba4-dd13aee4b374.png">
<img width="337" alt="Screenshot 2019-07-16 at 13 15 58" src="https://user-images.githubusercontent.com/50131232/61290467-3b34e500-a7cc-11e9-98c6-5aa9a001b99e.png">

**Comment by reusr1** [comment]
@Felix-Puetz is this still happening for you?

**Comment by flx-sta** [comment]
> @Felix-Puetz is this still happening for you?

No.

_But we also made some changes on our side so I can't guarantee if it was fixed_ 
Maybe a link to the commit/pr that fixed it?

**Comment by bkheadwire** [comment]
@Felix-Puetz looking at develop, I still see those styles on the row class, but I can't reproduce the cutoff issue. Was it happening to specific components or with particular settings on the components?

**Comment by FabianHaupt** [comment]
The Problem on our side existed when we put components directly in to Elements with the row class. As far as i understand the reason row uses a margin of negative 15 Pixel is that it comes from bootstrap and bootstrap intends to always have containers in rows. These container have a margin left and right of 15 Pixels so that there always is some space between them. But since they don't want the container furthest left and furthest right to habe space to the edge of the parent container they give the parent container the negative margin.
