### ISSUE TITLE
Two trumbowyg editor with different configs dont work properly

### ISSUE THREAD

**Issue by aaronseg** [headwirecom/peregrine-cms#252]
When adding two components with two different trumbowyg editor configurations the first component selected will overwrite the second config, when switching between the two components, without saving or closing.

![Screenvideo](https://user-images.githubusercontent.com/22643961/66393599-45cdd780-e9d3-11e9-9ae6-c6c9a197a3a6.gif)

**Comment by reusr1** [comment]
@aaronseg this issue is due to https://github.com/headwirecom/peregrine-cms/blob/cf253e97313edd23fbe9e9cf8f9ce8379fbbdcca/admin-base/ui.apps/src/main/content/jcr_root/apps/field/texteditor/template.vue#L107 - the changes made here by metaproc to support configurations of the editor are not reflected as the editor is only created once. If you hit ok after your edit before editing the next component the issue does not happen. We need to rethink the creation of the editor here to solve the problem.

**Comment by flx-sta** [comment]
Add follow-up issue to specify the problem
#301
