### ISSUE TITLE
publishing a page doesn't change the color of the globe anymore

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#348]
seems like this doesn't work properly anymore (Replication)

**Comment by reusr1** [comment]
@NMuzaffar assigning to you as this seems to be more of a backend issue. when clicking the globe icon you should see the content replicated into the file system at sling/staticreplication. This seems to not work anymore. Please have a look and address the issue (note, the globe icon had issues before, it would only change color when the view was refreshed, most likely due to the time it takes to replicate)

**Comment by NMuzaffar** [comment]
* Fixed the wrong references in content -> Pull commits from **themecleanflex**
* Added small check to DefaultMapperService to use **localFS** as default, and **local** for specific paths

**Comment by reusr1** [comment]
since publishing a page takes some time this action happens asynchronously. we currently do not have a way to track the status of the activation request in the back-end. closing this issue for now

**Comment by flx-sta** [comment]
@reusr1 couldn't we change the color when the request itself was successful then?
Some visual feedback would be good.

I mean. It may look like some false postive since its not verfied but at least some feedback to the user that the request was sent
