### ISSUE TITLE
Cannot create certain objects

### ISSUE THREAD

**Issue by dna113p** [headwirecom/peregrine-cms#36]
When using the create object wizard and selecting 'allfields' object from the example project I can no longer proceed past the second step. No console errors.

**Comment by devintuffy** [comment]
caused by: createObjectWizard/template.vue, line 169:

`return this.$refs.nameTab.validate()`

returns false.

This file defines `validator: this.nameAvailable`, which I would expect to bind validator() to this.nameAvailable, but isn't in this case; it's running the vue-form-generator validator() method instead. This can be found lines 158-197 here:  https://github.com/vue-generators/vue-form-generator/blob/master/src/formGenerator.vue

Based on the source I was able to step through the minified version of the code (not recommended), and here's the fields and results objects:

![Screen Shot 2019-03-13 at 11 07 48 AM](https://user-images.githubusercontent.com/46942507/54303676-c3864d80-4580-11e9-9bb4-1b61a9c1c834.png)

So it appears to be validating on a bunch of fields that are either hidden or in memory from some other module. Will keep on investigating.

(Note: we recently updated vue-form-generator, checking the version notes to see if there were any validation changes would be a good place to start)

**Comment by devintuffy** [comment]
This page has two forms, one which has what we expect, and the other which has a bunch of nonsense that is causing the validator to fail:

![Screen Shot 2019-03-13 at 11 21 29 AM](https://user-images.githubusercontent.com/46942507/54304524-95a20880-4582-11e9-904c-2de74e3d89ce.png)

This additional forms which is stopping the validator from passing is attached to the "tabPanel"  and is currently hidden:

![Screen Shot 2019-03-13 at 11 23 57 AM](https://user-images.githubusercontent.com/46942507/54304571-b0747d00-4582-11e9-96cb-ce9f0ec06e04.png)

Continuing to investigate.

**Comment by devintuffy** [comment]
So it looks like createObject is trying to validate the "name" and "verify" steps at the same time...ooh, because they both have the same attribute value for vue-form-generator -> ref. Fixing.
