### ISSUE TITLE
fix links in sample content when tenant is created 

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#444]
some links in the rich content are not changed to the new tenant urls when we create the content of a new tenant. (for example, footer links)

we need a way to make sure when we copy over string properties we check and fix A tags if they are pointing to content of the site itself.

**Comment by GastonGonzalez** [comment]
In order to reproduce this bug, you need to perform the following:
1. Deploy the latest `develop` branch of `themeclean-flex`.
2. Create a site.
3. View a page.
4. Inspect the links in the footer.

*Expected Behavior*
Links reflect the current tenant.

*Actual Behavior*
Links reflect the `/content/themecleanflex/pages/...` structure.

**Comment by GastonGonzalez** [comment]
@reusr1 - PR ready: https://github.com/headwirecom/peregrine-cms/pull/450

**Comment by reusr1** [comment]
works like a charm :-)
