### ISSUE TITLE
when creating a new tenant do not change path fields for content that is not copied

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#445]
in themecleanflex the node /content/themecleanflex/assets/samples is set to doNotCopy - if a property of any page points to an image under that path we should not change the tenant on that property

**Comment by GastonGonzalez** [comment]
The following are some tests cases based on the current build of themeclean flex.

1. `/content/themecleanflex/templates/base page/jcr:content/n1f964177-2026-4697-80ce-7ea78fa1b3e2` contains a reference to `/content/themecleanflex/assets/samples/sample-logo.png`

2. `/content/themecleanflex/templates/base page/jcr:content/nbeb05b9b-3df4-4d4a-a770-a2d7357912db` contains a reference to `/content/themecleanflex/assets/samples/sample-logo.png`

3. `/content/themecleanflex/pages/index/jcr:content/nebf8e89b-7765-4d9c-9e19-bff3f4d03a7b/nbd4db08a-f945-425c-a565-5e824304e07e` contains a reference to `/content/themecleanflex/assets/samples/beach-bird-s-eye-view-daytime-1249586.jpg`

**Comment by GastonGonzalez** [comment]
@reusr1 - Fixed in PR: https://github.com/headwirecom/peregrine-cms/pull/452

1. Deploy code.
2. Create a new site.
3. Navigate to site > page > home.
4. Edit the Teaser Vertical component and toggle Custom Background.

*Expected Behavior:*
The image reference should render and point to `/content/themecleanflex/assets/samples/beach-bird-s-eye-view-daytime-1249586.jpg`.

**Comment by GastonGonzalez** [comment]
@reusr1 - issues/444 and issues/445 are fixed with this PR: https://github.com/headwirecom/peregrine-cms/pull/452/files

**Comment by reusr1** [comment]
looks good @GastonGonzalez
