### ISSUE TITLE
do not copy replication state from theme when a tenant is created

### ISSUE THREAD

**Issue by reusr1** [headwirecom/peregrine-cms#473]
activate themecleanflex, then create a tenant based on themecleanflex. The new site shows the activation state from themecleanflex but that is not correct. In the tenant creation process the replication state should not be copied

**Comment by reusr1** [comment]
we should also make sure copying a page in general does not copy the replication state (see for example create new page with a skeleton page as the template)

**Comment by GastonGonzalez** [comment]
*Steps to Reproduce:*

1. Create a site.

2. Navigate to "yoursite" > "Settings" and click the "SITE SETUP REPLICATION" button. This will replicate all site assets to the file system (`sling/staticreplication/`).

3. Navigate back to "Pages" and create a page based on a skeleton page (i.e. "Article").

4. Notice that your new page has a purple globe icon. 

The process of copying a previously replicated skeleton page also copies the replication status to the new page. For example, our new page has the following JCR replication properties:

- per:Replicated 
- per:ReplicatedBy
- per:ReplicationRef

*Expected Behavior:*
The newly created page should not have replication properties since it has never been replicated.

**Comment by reggie7** [comment]
@reusr1 @GastonGonzalez looks fixed to me.
