### ISSUE TITLE
download site backup: macOS standard archiving program says archive invalid

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#502]
https://github.com/kestrel-1/report-an-issue/issues/7

> * macOS standard archiving program cannot open / read the downloaded site backup zip archive.

**Comment by flx-sta** [comment]
I've tried it on my MacOS Partition and it worked fine for me. Please verify again

**Comment by Thomas-Pelster** [comment]
- Problem still exists

![20200814_0955_Kestrel_backupfile_invalid](https://user-images.githubusercontent.com/50134764/90230430-d8bc7700-de19-11ea-8c28-2aa9d0cafd03.gif)

**Comment by flx-sta** [comment]
Tried it again on my system. Still could not reproduce it.
Maybe has to do with the Version of MacOS

**Comment by Thomas-Pelster** [comment]
After some research I can say that it is a specific Apple bug. This is due to the interpretation of the standard and probably has something to do with specific bits in the zip archive.

With unzip via terminal or e.g. UnArchiver it works without problems.

@reusr1  I would recommend to visualize only a hint on the page or an overlay after download, which says that the zip contains complex unicode data and not every standard program interprets it correctly, e. g. Apples standard desktop unarchiver.

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/20
