### ISSUE TITLE
Delete operation: reference issue

### ISSUE THREAD

**Issue by reggie7** [headwirecom/peregrine-cms#587]
[Use Case](https://github.com/headwirecom/peregrine-cms/pull/585#issuecomment-705182976)
1. Create a page (p1) and publish it.
2. Create a second page (p2). Add a card component and create a card that links to (p1). Publish p2.
3. Unpublish p1.
4. Delete p1.

Observed Behavior
1. p1 is allowed to be deleted.

Expected Behavior
1. p1 is referenced in p2. It should not be allowed for deletion.

**Comment by ehdatheadwire** [comment]
Looking at your noted behavior, @reggie7, I'd want to consider a notification of pending deletion rather than not allowing a page to be deleted. I'm moving this to the enhancements queue in the new repository so we can dig in a little bit more to the use case(s).

New location: https://github.com/peregrine-cms/enhancements/issues/54
