### ISSUE TITLE
Add support for a simple HTTP server

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#595]
In order to streamline the testing of the static file system replication implementation (i.e. localFS), a Maven profile shall be added that starts a Node.js HTTP server in the `staticreplication` folder.

https://www.npmjs.com/package/http-server

**Comment by reusr1** [comment]
@GastonGonzalez @reggie7 would it not be better to add this http-server to percli? this simple http server may be used outside of the maven infrastructure and by a developerr that only has node and docker installed on her/his computer

**Comment by reggie7** [comment]
I don't know, actually just tested it and it's pretty simple to set up by hand, so I would choose 3rd option to configure Docker image to do it on startup and local one is not on my personal wishlist :)
Other than that I think that since e.g. my server location in file system has nothing to do with where I store the codebase - I'm not sure how `mvn` would work with that.
Another idea from me would be this: let's somehow enable the `starter` to start the server for us in development. Sth like `java -jar ... --staticreplication-server`?

**Comment by ehdatheadwire** [comment]
Closing OG issue and relocating to: https://github.com/peregrine-cms/enhancements/issues/25
