### ISSUE TITLE
Create script to determine when Sling bundle versions change

### ISSUE THREAD

**Issue by GastonGonzalez** [headwirecom/peregrine-cms#606]
In order to keep Peregrine current with the latest version of Sling, currently Sling12, a script shall be created to determine which Sling dependencies our out of date.

**Comment by ehdatheadwire** [comment]
@GastonGonzalez and @reusr1 I removed the enhancement label as I don't think this is a candidate for the enhancements repository. Please correct me if I'm wrong, but this appears to be something related to sling12 and therefore might need to be worked on sooner rather than later. Let me know here either way. Thank you!

**Comment by GastonGonzalez** [comment]
@reusr1 - I believe you created a diff script for this? Can this be closed?

**Comment by reusr1** [comment]
moved issue to the correct repository: https://github.com/peregrine-cms/peregrine-builder/issues/1
