### ISSUE TITLE
QOL: easy initial grid system

### ISSUE THREAD

**Issue by flx-sta** [headwirecom/peregrine-cms#754]
Right now for a an author setting up a initial grid system is not really intuitive and takes a lot of initial effort.

Skeleton pages might not be the right solution here.

Maybe add an option to spawn a grid system similar to inserting a table in word

Looking forward to other ideas

**Comment by cmrockwell** [comment]
Creating custom layouts is currently possible using the Container and Container Block. This requires the users to know some tricks as well as some trial and error. One solution is to generate the grid like you suggested. Another approach is to allow setting of widths on more components directly, so the need for extra containers (block or plain) is less. This also may be a ticket better suited for the Themeclean Flex project

**Comment by reusr1** [comment]
it has long been my desire to move the creation of the default components from code to the editor interface. If we allow to edit the default examples instead of creating them from code we can easily for example provide a 2 and 3 column layout as we can create a component tree when dragging a component onto the page. This would at least make this use case easier to understand and more transparent to the user.

**Comment by flx-sta** [comment]
We will be adressing this in the future again
