### ISSUE TITLE
Redundant call to endpoint

### ISSUE THREAD

**Issue by ghost** [headwirecom/peregrine-cms#859]
After click we can see redundant call to endpoint  (Network in DevTools). It drains memory unnecessarily. 

**Steps to Reproduce**

1. Create a site.
2. Go to Pages. 
3. Click F12 for DevTools. Switch to Network there.
3. Click on the Page name or info or references.
4. See how redundant call appears.

**Expected behavior**
After click, there should be only one call. 

**Actual behavior**
There is a redundant call after click. 

**Screenshots** 

![call_endpoint_1](https://user-images.githubusercontent.com/1230506/114592835-a9515900-9c8b-11eb-8564-ad288b0288d5.png)

![Screenshot_6](https://user-images.githubusercontent.com/1230506/114595710-faaf1780-9c8e-11eb-8d90-8b971eec751b.png)

**Environment**

- LocalFS

- develop-sling12

- Chrome 88

- Windows 10 (64bit)

**Comment by flx-sta** [comment]
@KWoloszczuk Those are mot exatly redundant calls
If you open the request headers you can see that those are 2 completly different endpoiints:

![image](https://user-images.githubusercontent.com/50131232/115534409-06569b80-a298-11eb-9d50-e1f2dafab3e7.png)
![image](https://user-images.githubusercontent.com/50131232/115534424-0b1b4f80-a298-11eb-804a-0e176d284a3d.png)


but an addtional request when clicking on references was in fact an unnecessary call.

that what i fixed in #877

**Comment by reusr1** [comment]
closed, fix was merged and verified
